export const apps = [
    {
        name: 'kanata-bot',
        script: './src/index.js',
        instances: 1,
        exec_mode: 'fork',
        autorestart: true,
        watch: false,
        max_memory_restart: '2G',
        min_uptime: '15s',
        restart_delay: 5000,
        exp_backoff_restart_delay: 200,
        kill_timeout: 5000,
        listen_timeout: 10000,
        time: true,
        env: {
            NODE_ENV: 'production',
        },
        log_date_format: 'YYYY-MM-DD HH:mm:ss',
        error_file: './logs/pm2-err.log',
        out_file: './logs/pm2-out.log',
        combine_logs: true,
        merge_logs: true,
    },
    {
        name: 'kanata-core',
        cwd: './core',
        script: './src/server.js',
        instances: 1,
        exec_mode: 'fork',
        autorestart: true,
        watch: false,
        max_memory_restart: '1G',
        min_uptime: '15s',
        restart_delay: 5000,
        exp_backoff_restart_delay: 200,
        kill_timeout: 5000,
        time: true,
        env: {
            NODE_ENV: 'production',
        },
        log_date_format: 'YYYY-MM-DD HH:mm:ss',
        error_file: '../logs/core-err.log',
        out_file: '../logs/core-out.log',
        combine_logs: true,
        merge_logs: true,
    },
];
