import logger from '../../utils/logger.js';
export default {
    name: 'testrich',
    description: 'Explore AI Rich Responses (Table & Code)',
    category: 'Utility',
    execute: async (sock, m, args, text) => {
        const type = args[0]?.toLowerCase();

        const buildMsg = (submessages) => ({
            botForwardedMessage: {
                message: {
                    richResponseMessage: {
                        messageType: 1,
                        submessages,
                        contextInfo: {
                            forwardingScore: 1,
                            isForwarded: true,
                            forwardedAiBotMessageInfo: { botJid: '867051314767696@bot' },
                            forwardOrigin: 4,
                            stanzaId: m.key.id,
                            participant: m.sender,
                            quotedMessage: m.message,
                        },
                    },
                },
            },
            messageContextInfo: {
                botMetadata: {
                    messageDisclaimerText: 'Generated by Meta AI',
                },
            },
        });

        const tests = {
            table: [
                { messageType: 2, messageText: '📊 *NATIVE TABLE TEST*' },
                {
                    messageType: 4,
                    tableMetadata: {
                        title: 'System Status',
                        rows: [
                            { items: ['Service', 'Status', 'Ping'], isHeading: true },
                            { items: ['Database', 'Connected', '12ms'], isHeading: false },
                            { items: ['Storage', 'Available', '85%'], isHeading: false },
                        ],
                    },
                },
            ],
            code: [
                { messageType: 2, messageText: '💻 *CODE BLOCK TEST*' },
                {
                    messageType: 5,
                    codeMetadata: {
                        codeLanguage: 'javascript',
                        codeBlocks: [
                            { highlightType: 1, codeContent: 'const ' },
                            { highlightType: 0, codeContent: 'bot = ' },
                            { highlightType: 3, codeContent: "'Kanata'" },
                            { highlightType: 0, codeContent: ';\n' },
                            { highlightType: 1, codeContent: 'logger.info' },
                            { highlightType: 0, codeContent: '(bot);' },
                        ],
                    },
                },
            ],
        };

        if (!type || !tests[type]) {
            let help = `*── 「 RICH TEST HELP 」 ──*\n\n`;
            help += `Gunakan format: \`.testrich <type>\`\n\n`;
            help += `*Available Types:*\n`;
            Object.keys(tests).forEach((t) => {
                help += `➛ ${t}\n`;
            });
            return m.reply(help);
        }

        const msg = buildMsg(tests[type]);
        await sock.relayMessage(m.chat, msg, { messageId: sock.generateMessageTag() });
    },
};
