/**
 * Pinterest Search Scraper v6 - Puppeteer + Netscape Cookies
 * Usage: node unused/scrape_pinterests.js "mirai kuriyama"
 *
 * Combines Puppeteer rendering with fresh Netscape cookies.
 * Query is dynamic (CLI arg).
 */

import puppeteer from 'puppeteer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import * as cheerio from 'cheerio';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Netscape cookie data (fresh dari user)
const NETSCAPE_COOKIE_DATA = `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
id.pinterest.com	FALSE	/	FALSE	1799809421	g_state	{"i_l":0,"i_ll":1784257421644,"i_b":"0lxJPEI0owKHR6ml7468ycofO5JxnjASOBrM4y/pF3s","i_e":{"enable_itp_optimization":24},"i_et":1784257421644}
id.pinterest.com	FALSE	/	TRUE	1787025223	csrftoken	cb2840e30da20bf4c1b3130211884101
#HttpOnly_id.pinterest.com	FALSE	/	FALSE	1784343229	_routing_id	"a2f49ad0-6fc1-4439-9f44-5d369c2e99c2"
.pinterest.com	TRUE	/	FALSE	1810784665	_b	"AZNDwjyOHs5CabXN1yP/y5MyvNkxKwyXEGW0lLZuCS+Q3XdJkIvP5s3inPAK53dXSZ4="
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_pinterest_sess	TWc9PSZJTUc4d2NQVmt4cmFWN3pQaXNJOURvaVZvczI2bVZKSmhKK0xFQXVlLzJWQkdubWRiWWZKMjdLN0pUOGZQL3B2TW52OWVsM1hDZ0NTaS9laEhLMDFZUVpMemlLUWFUelJoZDM3N1VEZVFwTjM5Z21ad2txdGIzYjZybzdueEpUME1qU2o2Smc0QXpMNjlCMXZBSlM4QVBNQVo3cTVxSFRnZmJBbHRCaU9Sb0xiQ1h4QkFzcE5xRFFzbVd2UkR6OVk0MEJMdjMzVlZnZjMzUU9Zc0NZaTZXZGx6cW5FdjhWS0dYS2xCSGxlRC9RYWlzUy9uOG5YSmdBTkNXaUdJaTRlU00xYVZ1ck9UWTdvNWpXcU42U2d3b1RNeUhNSG9CSUNvdWVoVkV6Z2VleXFGVmc1b1FSQTIwaGZ6RGJaYjJwNEJFSWRBMXlhaytCQnRjeVcwSENmR3RnSFh3STJ3TE5zbmkzdEhBYXp5NXhaOUNYS0hlY21VR2NqWjgzRnpGbGtqeXRUZHBEMERNVk1RZmYwNlVreUdnPT0mRVNENWhMVExTNEFqRUtJUCt4Smxsdllsbmc0PQ==
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1815634075	usersync	%7B%22magnite%22%3A%7B%22id%22%3A%22MC3IL7OY-1M-30XT%22%2C%22ts%22%3A1784098076459%7D%7D
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	__Secure-s_a	djhOckxoeUNYQW1DT3owWXBNY3lmUHZ6SCtFQjBmKzZUUzRJcUsxeW5PN2xiS1FucVF3dDFPY1llczFrRHV1cmxyTmMwRGVPKytLLzRyeGpBaWpYTE00a3dLZlpYT1NXZUFWLzBaMGpkQ0w1ditwUWt3M3VGQy9iSzhseEJJRlF2RDRuL3E1NHhYVmpqcHk3WXBLb0NvZ1lVSHdWcCtCcThFUEhUMUhVRGJrNDRXT3pVN1V6VXJIdG1Tdm9pWVc0NkhZVnM1RU8vUTZDOU9hYmYvRzVWRUl4NmJhVC9vV0M1WmVzdExXUDFucmJ1VHR0ZmUyN2tQWEd6TGRIVXczTytzdkY3dUVBK3VSeEhiZW5rUjIvNmprVE96dkQrNFJMMGVaOWFGRjN4b289JlFhMytqeGFtL1RuN3pSd0pocThjaG5WNGV4az0=
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_auth	1
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1808974505	ar_debug	1
#HttpOnly_id.pinterest.com	FALSE	/	TRUE	1791265976	ar_debug	1
id.pinterest.com	FALSE	/	TRUE	1784300033	sessionFunnelEventLogged	1`;

/**
 * Parse Netscape cookie file format to Puppeteer cookie objects
 */
function parseNetscapeForPuppeteer(cookieData) {
    const cookies = [];
    const lines = cookieData.split('\n');

    for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed.startsWith('#') || trimmed === '') continue;

        const cleanLine = trimmed.replace(/^#HttpOnly_/, '');
        const parts = cleanLine.split('\t');
        if (parts.length >= 7) {
            const [domain, flag, cookiePath, secure, expiry, name, ...valueParts] = parts;
            let value = valueParts.join('\t');
            if (value.startsWith('"') && value.endsWith('"')) {
                value = value.slice(1, -1);
            }

            cookies.push({
                name,
                value,
                domain: domain.startsWith('.') ? domain : domain,
                path: cookiePath || '/',
                secure: secure === 'TRUE',
                httpOnly: trimmed.startsWith('#HttpOnly_'),
                expires: parseInt(expiry) || -1,
            });
        }
    }
    return cookies;
}

async function scrapePinterest(query) {
    const searchUrl = `https://id.pinterest.com/search/pins/?q=${encodeURIComponent(query)}&rs=typed`;
    const outputDir = path.join(__dirname, '..', 'results');
    await fs.ensureDir(outputDir);

    console.log('='.repeat(60));
    console.log('  Pinterest Scraper v6 - Puppeteer + Netscape Cookies');
    console.log(`  Query: "${query}"`);
    console.log('='.repeat(60));

    const browser = await puppeteer.launch({
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--hide-scrollbars',
            '--disable-blink-features=AutomationControlled',
            '--window-size=1920,1080',
        ],
    });

    try {
        const page = await browser.newPage();

        // Anti-detection evasions
        await page.setUserAgent(
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
        );
        await page.setViewport({ width: 1920, height: 1080 });

        await page.evaluateOnNewDocument(() => {
            Object.defineProperty(navigator, 'webdriver', { get: () => false });
            Object.defineProperty(navigator, 'plugins', {
                get: () => [1, 2, 3, 4, 5],
            });
            Object.defineProperty(navigator, 'languages', {
                get: () => ['en-US', 'en', 'id'],
            });
            window.chrome = { runtime: {}, loadTimes: () => {}, csi: () => {}, app: {} };
        });

        // Step 1: Go to pinterest.com first, set cookies
        console.log('🌐 Opening Pinterest home...');
        await page.goto('https://id.pinterest.com/', {
            waitUntil: 'networkidle2',
            timeout: 30000,
        });

        // Step 2: Set cookies
        const cookies = parseNetscapeForPuppeteer(NETSCAPE_COOKIE_DATA);
        console.log(`🍪 Setting ${cookies.length} cookies...`);
        await page.setCookie(...cookies);

        // Step 3: Reload to verify login
        await page.goto('https://id.pinterest.com/', {
            waitUntil: 'networkidle2',
            timeout: 30000,
        });

        const currentUrl = page.url();
        const pageContent = await page.content();
        const isLoggedIn = !currentUrl.includes('/login/') && !pageContent.includes('Log in');
        console.log(`🔐 Login: ${isLoggedIn ? '✅ LOGGED IN' : '❌ NOT LOGGED IN'}`);

        if (!isLoggedIn) {
            console.log('⚠️  Cookies not working for login. Trying search anyway...');
        }

        // Step 4: Navigate to search
        console.log(`\n🔍 Searching: "${query}"`);
        await page.goto(searchUrl, {
            waitUntil: 'networkidle2',
            timeout: 60000,
        });

        console.log(`📍 Final URL: ${page.url()}`);
        const title = await page.title();
        console.log(`📄 Title: ${title}`);

        // Step 5: Scroll to trigger lazy loading
        console.log('🖱️ Scrolling...');
        for (let i = 0; i < 8; i++) {
            await page.evaluate(() => {
                window.scrollBy(0, window.innerHeight);
            });
            await new Promise((r) => setTimeout(r, 2000));
        }

        // Step 6: Extract images - using pinimg approach which worked before
        console.log('🔎 Extracting images...');

        // Take screenshot
        await page.screenshot({
            path: path.join(outputDir, `pinterest_v6_${query.replace(/\s+/g, '_')}.png`),
            fullPage: false,
        });

        // Get page HTML
        const html = await page.content();
        await fs.writeFile(path.join(outputDir, 'pinterest_v6_page.html'), html.slice(0, 500000));

        // Method A: Extract all pinimg images from DOM
        const pins = await page.evaluate(() => {
            const results = [];
            const seen = new Set();
            const imgs = document.querySelectorAll('img[src*="pinimg"]');

            imgs.forEach((img) => {
                const src = img.src || img.getAttribute('src') || '';
                // Skip avatars, logos, icons
                if (
                    src.includes('/avatars/') ||
                    src.includes('/favicon') ||
                    src.includes('logo') ||
                    src.includes('profile') ||
                    src.includes('icon')
                )
                    return;

                // Skip very small images (likely icons/ui)
                const w = img.naturalWidth || img.width;
                if (w && w < 50) return;

                // Find parent link
                const parentLink = img.closest('a');
                const link = parentLink
                    ? parentLink.href || parentLink.getAttribute('href') || ''
                    : '';
                const alt = img.alt || '';

                // Build full link
                let fullUrl = link;
                if (fullUrl.startsWith('/')) {
                    fullUrl = 'https://id.pinterest.com' + fullUrl;
                }

                // Extract pin ID from URL
                let pinId = '';
                const idMatch = fullUrl.match(/\/pin\/(\d+)/);
                if (idMatch) pinId = idMatch[1];

                const key = src;
                if (!seen.has(key)) {
                    seen.add(key);
                    results.push({
                        id: pinId,
                        title: alt,
                        thumbnail: src,
                        hq: src.replace(/\/\d+x\//, '/originals/'),
                        hq_736: src.replace(/\/\d+x\//, '/736x/'),
                        link: fullUrl,
                        description: alt,
                    });
                }
            });

            return results;
        });

        console.log(`✅ Found ${pins.length} images`);

        // Save results
        const timestamp = Date.now();
        const outputPath = path.join(outputDir, `pinterest_v6_${timestamp}.json`);
        await fs.writeJson(outputPath, pins, { spaces: 2 });
        console.log(`💾 Saved to: ${outputPath}`);

        // Save HQ URLs only
        const txtPath = path.join(outputDir, `${query.replace(/\s+/g, '_')}_hq_urls.txt`);
        await fs.writeFile(txtPath, pins.map((p) => p.hq).join('\n'));
        console.log(`💾 HQ URLs saved to: ${txtPath}`);

        // Display preview
        console.log('\n📌 Top Results:');
        pins.slice(0, 10).forEach((pin, i) => {
            console.log(`  [${i + 1}] ${pin.title || '(no title)'}`);
            if (pin.id) console.log(`       Pin ID: ${pin.id}`);
            if (pin.hq) console.log(`       HQ: ${pin.hq.slice(0, 90)}...`);
            if (pin.link) console.log(`       Link: ${pin.link.slice(0, 100)}`);
        });

        return pins;
    } catch (err) {
        console.error('❌ Error:', err.message);
        return [];
    } finally {
        await browser.close();
        console.log('\n🛑 Browser done');
    }
}

// ===== MAIN =====
const query = process.argv[2] || 'mirai kuriyama';
scrapePinterest(query)
    .then((pins) => {
        console.log(`\n✅ Total: ${pins.length} gambar`);
        process.exit(0);
    })
    .catch((err) => {
        console.error('Fatal:', err.message);
        process.exit(1);
    });
