/**
 * Pinterest Search Scraper v5 - Netscape Cookie + RSS Feed
 * Usage: node unused/scrape_pinterest_netscape.js "mirai kuriyama"
 *
 * Parses Netscape cookie file format, fetches Pinterest RSS feed.
 * Query is dynamic (from command line arg).
 *
 * Cookie format (Netscape):
 *   domain  flag  path  secure  expiry  name  value
 */

import axios from 'axios';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import * as cheerio from 'cheerio';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// === Netscape Cookie File ===
// Pasted from user
const NETSCAPE_COOKIE_DATA = `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
id.pinterest.com	FALSE	/	FALSE	1799809421	g_state	{"i_l":0,"i_ll":1784257421644,"i_b":"0lxJPEI0owKHR6ml7468ycofO5JxnjASOBrM4y/pF3s","i_e":{"enable_itp_optimization":24},"i_et":1784257421644}
id.pinterest.com	FALSE	/	TRUE	1787025223	csrftoken	cb2840e30da20bf4c1b3130211884101
#HttpOnly_id.pinterest.com	FALSE	/	FALSE	1784343229	_routing_id	"a2f49ad0-6fc1-4439-9f44-5d369c2e99c2"
.pinterest.com	TRUE	/	FALSE	1810784665	_b	"AZNDwjyOHs5CabXN1yP/y5MyvNkxKwyXEGW0lLZuCS+Q3XdJkIvP5s3inPAK53dXSZ4="
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_pinterest_sess	TWc9PSZJTUc4d2NQVmt4cmFWN3pQaXNJOURvaVZvczI2bVZKSmhKK0xFQXVlLzJWQkdubWRiWWZKMjdLN0pUOGZQL3B2TW52OWVsM1hDZ0NTaS9laEhLMDFZUVpMemlLUWFUelJoZDM3N1VEZVFwTjM5Z21ad2txdGIzYjZybzdueEpUME1qU2o2Smc0QXpMNjlCMXZBSlM4QVBNQVo3cTVxSFRnZmJBbHRCaU9Sb0xiQ1h4QkFzcE5xRFFzbVd2UkR6OVk0MEJMdjMzVlZnZjMzUU9Zc0NZaTZXZGx6cW5FdjhWS0dYS2xCSGxlRC9RYWlzUy9uOG5YSmdBTkNXaUdJaTRlU00xYVZ1ck9UWTdvNWpXcU42U2d3b1RNeUhNSG9CSUNvdWVoVkV6Z2VleXFGVmc1b1FSQTIwaGZ6RGJaYjJwNEJFSWRBMXlhaytCQnRjeVcwSENmR3RnSFh3STJ3TE5zbmkzdEhBYXp5NXhaOUNYS0hlY21VR2NqWjgzRnpGbGtqeXRUZHBEMERNVk1RZmYwNlVreUdnPT0mRVNENWhMVExTNEFqRUtJUCt4Smxsdllsbmc0PQ==
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1815634075	usersync	%7B%22magnite%22%3A%7B%22id%22%3A%22MC3IL7OY-1M-30XT%22%2C%22ts%22%3A1784098076459%7D%7D
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	__Secure-s_a	djhOckxoeUNYQW1DT3owWXBNY3lmUHZ6SCtFQjBmKzZUUzRJcUsxeW5PN2xiS1FucVF3dDFPY1llczFrRHV1cmxyTmMwRGVPKytLLzRyeGpBaWpYTE00a3dLZlpYT1NXZUFWLzBaMGpkQ0w1ditwUWt3M3VGQy9iSzhseEJJRlF2RDRuL3E1NHhYVmpqcHk3WXBLb0NvZ1lVSHdWcCtCcThFUEhUMUhVRGJrNDRXT3pVN1V6VXJIdG1Tdm9pWVc0NkhZVnM1RU8vUTZDOU9hYmYvRzVWRUl4NmJhVC9vV0M1WmVzdExXUDFucmJ1VHR0ZmUyN2tQWEd6TGRIVXczTytzdkY3dUVBK3VSeEhiZW5rUjIvNmprVE96dkQrNFJMMGVaOWFGRjN4b289JlFhMytqeGFtL1RuN3pSd0pocThjaG5WNGV4az0=
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_auth	1
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1808974505	ar_debug	1
#HttpOnly_id.pinterest.com	FALSE	/	TRUE	1791265976	ar_debug	1
id.pinterest.com	FALSE	/	TRUE	1784300033	sessionFunnelEventLogged	1`;

/**
 * Parse Netscape cookie file format into a cookie string
 */
function parseNetscapeCookies(cookieData) {
    const cookies = [];
    const lines = cookieData.split('\n');

    for (const line of lines) {
        const trimmed = line.trim();
        // Skip comments and empty lines
        if (trimmed.startsWith('#') || trimmed === '') continue;

        // Skip HttpOnly prefix if present
        const cleanLine = trimmed.replace(/^#HttpOnly_/, '');

        const parts = cleanLine.split('\t');
        if (parts.length >= 7) {
            const [domain, flag, path, secure, expiry, name, ...valueParts] = parts;
            let value = valueParts.join('\t');

            // Remove surrounding quotes if present
            if (value.startsWith('"') && value.endsWith('"')) {
                value = value.slice(1, -1);
            }

            cookies.push({ name, value, domain, path, secure: secure === 'TRUE' });
        }
    }

    // Build cookie string for HTTP header
    return cookies.map((c) => `${c.name}=${c.value}`).join('; ');
}

/**
 * Parse RSS XML to extract items
 */
function parseRSS(xml) {
    const $ = cheerio.load(xml, { xmlMode: true });
    const items = [];

    // Try RSS 2.0 format
    $('rss channel item').each((i, el) => {
        const $item = $(el);
        items.push({
            title: $item.find('title').text() || '',
            link: $item.find('link').text() || '',
            guid: $item.find('guid').text() || '',
            description: $item.find('description').text() || '',
            pubDate: $item.find('pubDate').text() || '',
            author: $item.find('author').text() || $item.find('dc\\:creator').text() || '',
            enclosure: $item.find('enclosure').attr('url') || '',
            mediaContent: $item.find('media\\:content').attr('url') || '',
            mediaThumbnail: $item.find('media\\:thumbnail').attr('url') || '',
        });
    });

    // Try Atom format
    $('feed entry').each((i, el) => {
        const $item = $(el);
        items.push({
            title: $item.find('title').text() || '',
            link: $item.find('link').attr('href') || '',
            guid: $item.find('id').text() || '',
            description: $item.find('summary').text() || $item.find('content').text() || '',
            pubDate: $item.find('published').text() || $item.find('updated').text() || '',
            author: $item.find('author name').text() || '',
            enclosure: $item.find('enclosure').attr('url') || '',
            mediaContent: $item.find('media\\:content').attr('url') || '',
            mediaThumbnail: $item.find('media\\:thumbnail').attr('url') || '',
        });
    });

    return items;
}

/**
 * Get image URL from a pin entry
 */
function getBestImage(item) {
    // From enclosure
    if (item.enclosure) return item.enclosure;
    // From media:content
    if (item.mediaContent) return item.mediaContent;
    // From media:thumbnail
    if (item.mediaThumbnail) return item.mediaThumbnail;
    // Try to extract from description (often contains <img> tag in RSS)
    if (item.description) {
        const imgMatch = item.description.match(/src=["']([^"']+)["']/i);
        if (imgMatch) return imgMatch[1];
    }
    return '';
}

/**
 * Extract pin ID from URL
 */
function extractPinId(link) {
    const match = link.match(/\/pin\/(\d+)/);
    return match ? match[1] : '';
}

/**
 * Main scrape function
 */
async function scrapePinterest(query) {
    const cookieStr = parseNetscapeCookies(NETSCAPE_COOKIE_DATA);
    const rssUrl = `https://id.pinterest.com/search/pins/?q=${encodeURIComponent(query)}&rs=typed&format=rss`;
    const outputDir = path.join(__dirname, '..', 'results');
    await fs.ensureDir(outputDir);

    console.log('='.repeat(60));
    console.log(`  Pinterest Scraper v5 - RSS + Netscape Cookie`);
    console.log(`  Query: "${query}"`);
    console.log(`  URL: ${rssUrl}`);
    console.log('='.repeat(60));

    // Extract CSRF token from cookies
    const csrfMatch = cookieStr.match(/csrftoken=([^;]+)/);
    const csrfToken = csrfMatch ? csrfMatch[1] : '';
    console.log(`🔑 CSRF Token: ${csrfToken ? csrfToken.slice(0, 20) + '...' : 'NOT FOUND'}`);

    const USER_AGENT =
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

    try {
        const response = await axios.get(rssUrl, {
            headers: {
                'User-Agent': USER_AGENT,
                Accept: 'application/rss+xml, application/xml, text/xml, application/json, text/html, */*; q=0.01',
                'Accept-Language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7',
                'X-Requested-With': 'XMLHttpRequest',
                'X-CSRFToken': csrfToken,
                Cookie: cookieStr,
                Referer: 'https://id.pinterest.com/',
                'Sec-Fetch-Dest': 'empty',
                'Sec-Fetch-Mode': 'cors',
                'Sec-Fetch-Site': 'same-origin',
            },
            timeout: 30000,
            maxRedirects: 5,
            validateStatus: (status) => status < 400,
        });

        const finalUrl = response.request?.res?.responseUrl || rssUrl;
        console.log(`\n📡 Status: ${response.status}`);
        console.log(`📍 Final URL: ${finalUrl}`);
        console.log(`📦 Content-Type: ${response.headers['content-type'] || 'unknown'}`);

        // Check if redirected to login
        if (finalUrl.includes('/login/')) {
            console.log('⚠️  Redirected to login! Cookies mungkin expired.');
        }

        const data = response.data;

        // Try to parse as XML/RSS
        const items = parseRSS(data);

        if (items.length > 0) {
            console.log(`\n✅ Found ${items.length} items in RSS feed!`);
        } else {
            console.log(`\n⚠️  No items found in RSS. Checking response type...`);

            const isHTML =
                typeof data === 'string' && (data.includes('<html') || data.includes('<!DOCTYPE'));
            const isJSON =
                typeof data === 'object' ||
                (typeof data === 'string' && data.trim().startsWith('{'));

            if (isHTML) {
                console.log(
                    '   Response is HTML (not RSS). Pinterest mungkin ga support RSS untuk query ini.'
                );
                // Save HTML for debugging
                await fs.writeFile(path.join(outputDir, 'pinterest_rss_debug.html'), data);
                console.log('   💾 Saved HTML to results/pinterest_rss_debug.html');

                // Try to extract images from HTML anyway
                const $ = cheerio.load(data);
                const imgs = [];
                $('img[src*="pinimg"]').each((i, el) => {
                    const src = $(el).attr('src');
                    if (src && !src.includes('avatars') && !src.includes('favicon')) {
                        imgs.push(src);
                    }
                });
                console.log(`   Found ${imgs.length} pin images in HTML`);

                if (imgs.length > 0) {
                    return imgs.map((src, i) => ({
                        index: i + 1,
                        thumbnail: src,
                        hq: src.replace(/\/\d+x\//, '/originals/'),
                        hq_736: src.replace(/\/\d+x\//, '/736x/'),
                    }));
                }
                return [];
            }

            if (isJSON) {
                console.log('   Response is JSON');
                const jsonData = typeof data === 'string' ? JSON.parse(data) : data;
                console.log(`   JSON keys: ${Object.keys(jsonData).join(', ')}`);
                await fs.writeJson(path.join(outputDir, 'pinterest_rss_json.json'), jsonData, {
                    spaces: 2,
                });
            }
        }

        // Process items
        const pins = items.map((item, i) => {
            const img = getBestImage(item);
            const pinId = extractPinId(item.link || item.guid);
            const hq = img ? img.replace(/\/\d+x\//, '/originals/') : '';
            const hq736 = img ? img.replace(/\/\d+x\//, '/736x/') : '';

            return {
                index: i + 1,
                id: pinId || item.guid,
                title: item.title,
                description: item.description.replace(/<[^>]+>/g, '').trim(),
                author: item.author,
                thumbnail: img,
                hq: hq,
                hq_736: hq736,
                link: item.link || item.guid,
            };
        });

        return pins;
    } catch (err) {
        if (err.response) {
            console.log(`\n❌ HTTP ${err.response.status}: ${err.response.statusText}`);
            console.log(`   Location: ${err.response.headers?.location || 'none'}`);
        } else {
            console.log(`\n❌ Error: ${err.message}`);
        }
        return [];
    }
}

// === MAIN ===
async function main() {
    const query = process.argv[2] || 'mirai kuriyama';
    const outputDir = path.join(__dirname, '..', 'results');
    await fs.ensureDir(outputDir);

    const pins = await scrapePinterest(query);

    if (pins.length > 0) {
        const timestamp = Date.now();
        const outputPath = path.join(outputDir, `pinterest_netscape_${timestamp}.json`);
        await fs.writeJson(outputPath, pins, { spaces: 2 });
        console.log(`\n💾 Saved to: ${outputPath}`);

        // Save HQ URLs as text
        const txtPath = path.join(outputDir, `pinterest_${query.replace(/\s+/g, '_')}_hq_urls.txt`);
        const urls = pins.map((p) => p.hq || p.thumbnail).filter(Boolean);
        await fs.writeFile(txtPath, urls.join('\n'));
        console.log(`💾 HQ URLs saved to: ${txtPath}`);

        console.log('\n📌 Results:');
        pins.slice(0, 15).forEach((pin) => {
            const title = pin.title || '(no title)';
            const img = (pin.hq || pin.thumbnail || '').slice(0, 90);
            console.log(`  [${pin.index}] ${title}`);
            if (pin.author) console.log(`       Author: ${pin.author}`);
            if (img) console.log(`       Image: ${img}...`);
            if (pin.link) console.log(`       Link: ${pin.link.slice(0, 100)}`);
        });

        console.log(`\n✅ Total: ${pins.length} pins`);
    } else {
        console.log('\n⚠️  No pins found.');
    }
}

main().catch(console.error);
