/**
 * Pinterest Search Scraper FINAL - Direct API
 * Usage: node unused/scrape_pinterest_final.js "mirai kuriyama"
 *
 * Langsung panggil API internal Pinterest /resource/BaseSearchResource/get/
 * Pake Netscape cookies. Ga perlu Puppeteer.
 */

import axios from 'axios';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// === Netscape cookies (fresh) ===
const NETSCAPE_DATA = `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
id.pinterest.com	FALSE	/	FALSE	1799809421	g_state	{"i_l":0,"i_ll":1784257421644,"i_b":"0lxJPEI0owKHR6ml7468ycofO5JxnjASOBrM4y/pF3s","i_e":{"enable_itp_optimization":24},"i_et":1784257421644}
id.pinterest.com	FALSE	/	TRUE	1787025223	csrftoken	cb2840e30da20bf4c1b3130211884101
#HttpOnly_id.pinterest.com	FALSE	/	FALSE	1784343229	_routing_id	"a2f49ad0-6fc1-4439-9f44-5d369c2e99c2"
.pinterest.com	TRUE	/	FALSE	1810784665	_b	"AZNDwjyOHs5CabXN1yP/y5MyvNkxKwyXEGW0lLZuCS+Q3XdJkIvP5s3inPAK53dXSZ4="
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_pinterest_sess	TWc9PSZJTUc4d2NQVmt4cmFWN3pQaXNJOURvaVZvczI2bVZKSmhKK0xFQXVlLzJWQkdubWRiWWZKMjdLN0pUOGZQL3B2TW52OWVsM1hDZ0NTaS9laEhLMDFZUVpMemlLUWFUelJoZDM3N1VEZVFwTjM5Z21ad2txdGIzYjZybzdueEpUME1qU2o2Smc0QXpMNjlCMXZBSlM4QVBNQVo3cTVxSFRnZmJBbHRCaU9Sb0xiQ1h4QkFzcE5xRFFzbVd2UkR6OVk0MEJMdjMzVlZnZjMzUU9Zc0NZaTZXZGx6cW5FdjhWS0dYS2xCSGxlRC9RYWlzUy9uOG5YSmdBTkNXaUdJaTRlU00xYVZ1ck9UWTdvNWpXcU42U2d3b1RNeUhNSG9CSUNvdWVoVkV6Z2VleXFGVmc1b1FSQTIwaGZ6RGJaYjJwNEJFSWRBMXlhaytCQnRjeVcwSENmR3RnSFh3STJ3TE5zbmkzdEhBYXp5NXhaOUNYS0hlY21VR2NqWjgzRnpGbGtqeXRUZHBEMERNVk1RZmYwNlVreUdnPT0mRVNENWhMVExTNEFqRUtJUCt4Smxsdllsbmc0PQ==
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1815634075	usersync	%7B%22magnite%22%3A%7B%22id%22%3A%22MC3IL7OY-1M-30XT%22%2C%22ts%22%3A1784098076459%7D%7D
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	__Secure-s_a	djhOckxoeUNYQW1DT3owWXBNY3lmUHZ6SCtFQjBmKzZUUzRJcUsxeW5PN2xiS1FucVF3dDFPY1llczFrRHV1cmxyTmMwRGVPKytLLzRyeGpBaWpYTE00a3dLZlpYT1NXZUFWLzBaMGpkQ0w1ditwUWt3M3VGQy9iSzhseEJJRlF2RDRuL3E1NHhYVmpqcHk3WXBLb0NvZ1lVSHdWcCtCcThFUEhUMUhVRGJrNDRXT3pVN1V6VXJIdG1Tdm9pWVc0NkhZVnM1RU8vUTZDOU9hYmYvRzVWRUl4NmJhVC9vV0M1WmVzdExXUDFucmJ1VHR0ZmUyN2tQWEd6TGRIVXczTytzdkY3dUVBK3VSeEhiZW5rUjIvNmprVE96dkQrNFJMMGVaOWFGRjN4b289JlFhMytqeGFtL1RuN3pSd0pocThjaG5WNGV4az0=
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_auth	1
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1808974505	ar_debug	1
#HttpOnly_id.pinterest.com	FALSE	/	TRUE	1791265976	ar_debug	1
id.pinterest.com	FALSE	/	TRUE	1784300033	sessionFunnelEventLogged	1`;

function parseCookieStr(data) {
    const cookies = [];
    for (const line of data.split('\n')) {
        const t = line.trim();
        if (t.startsWith('#') || !t) continue;
        const p = t.replace(/^#HttpOnly_/, '').split('\t');
        if (p.length >= 7) {
            let v = p.slice(6).join('\t');
            if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
            cookies.push(`${p[5]}=${v}`);
        }
    }
    return cookies.join('; ');
}

/**
 * Panggil API BaseSearchResource untuk search pins
 */
async function searchPins(query, bookmark = null) {
    const options = {
        query: query,
        scope: 'pins',
        rs: 'typed',
        page_size: 25,
        bookmarks: bookmark ? [bookmark] : undefined,
    };

    const data = JSON.stringify({
        options: bookmark ? { ...options, bookmarks: [bookmark] } : options,
        context: {},
    });
    const sourceUrl = `/search/pins/?q=${encodeURIComponent(query)}&rs=typed`;
    const url = `https://id.pinterest.com/resource/BaseSearchResource/get/?source_url=${encodeURIComponent(sourceUrl)}&data=${encodeURIComponent(data)}&_=${Date.now()}`;

    const cookieStr = parseCookieStr(NETSCAPE_DATA);
    const csrfToken = (cookieStr.match(/csrftoken=([^;]+)/) || [])[1] || '';

    const headers = {
        'User-Agent':
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
        Accept: 'application/json, text/javascript, */*; q=0.01',
        'Accept-Language': 'id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7',
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRFToken': csrfToken,
        Cookie: cookieStr,
        Referer: 'https://id.pinterest.com/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
    };

    const res = await axios.get(url, { headers, timeout: 30000, maxRedirects: 3 });

    if (res.status !== 200) {
        throw new Error(`HTTP ${res.status}`);
    }

    return res.data;
}

/**
 * Extract pins from response data
 */
function extractPins(data) {
    const pins = [];
    const resource = data?.resource_response?.data;

    if (!resource) return pins;

    // resource_response.data bisa array of pins atau object
    const items = Array.isArray(resource) ? resource : resource.results || [];

    for (const item of items) {
        // Pin structure
        if (item?.type === 'pin' || item?.images || item?.image) {
            const images = item.images || item.image || {};
            const orig = images.orig || images.originals || {};
            const url =
                orig.url || images['736x']?.url || images['564x']?.url || images['236x']?.url || '';

            pins.push({
                id: String(item.id || ''),
                title:
                    item.title ||
                    item.grid_title ||
                    item.description ||
                    item.pinner?.full_name ||
                    '',
                image: url,
                thumbnail: images['236x']?.url || images['170x']?.url || url,
                hq: images.originals?.url || images.orig?.url || url,
                hq_736: images['736x']?.url || url,
                link: `https://www.pinterest.com/pin/${item.id}/`,
                description: item.description || item.title || '',
                pinner: item.pinner?.full_name || item.pinner?.username || '',
                dominant_color: item.dominant_color || null,
            });
        }
    }

    return pins;
}

/**
 * Get bookmark for pagination
 */
function getBookmark(data) {
    return data?.resource_response?.bookmark || data?.resource?.options?.bookmarks?.[0] || null;
}

async function main() {
    const query = process.argv[2] || 'mirai kuriyama';
    const outputDir = path.join(__dirname, '..', 'results');
    await fs.ensureDir(outputDir);

    console.log('='.repeat(60));
    console.log('  Pinterest FINAL - Direct API');
    console.log(`  Query: "${query}"`);
    console.log('='.repeat(60));

    let allPins = [];
    let bookmark = null;
    let page = 1;
    const MAX_PAGES = 4; // Ambil 4 halaman (~100 pins)

    for (page = 1; page <= MAX_PAGES; page++) {
        console.log(`\n📡 Page ${page}...`);
        try {
            const data = await searchPins(query, bookmark);

            const pins = extractPins(data);
            console.log(`   Found ${pins.length} pins`);

            allPins.push(...pins);

            bookmark = getBookmark(data);
            if (!bookmark || bookmark === '-end-') {
                console.log('   📄 No more pages');
                break;
            }

            // Small delay between requests
            await new Promise((r) => setTimeout(r, 1000));
        } catch (err) {
            console.log(`   ❌ Error: ${err.message}`);
            break;
        }
    }

    // Deduplicate by ID or image
    const seen = new Set();
    allPins = allPins.filter((p) => {
        const key = p.id || p.image;
        if (!key || seen.has(key)) return false;
        seen.add(key);
        return true;
    });

    console.log(`\n${'='.repeat(60)}`);
    console.log(`✅ Total unique pins: ${allPins.length}`);

    // Save
    const timestamp = Date.now();
    const outJson = path.join(outputDir, `pinterest_final_${timestamp}.json`);
    await fs.writeJson(outJson, allPins, { spaces: 2 });
    console.log(`💾 JSON: ${outJson}`);

    // Save HQ URLs as text
    const outTxt = path.join(outputDir, `${query.replace(/\s+/g, '_')}_hq_urls.txt`);
    await fs.writeFile(
        outTxt,
        allPins
            .map((p) => p.hq || p.image)
            .filter(Boolean)
            .join('\n')
    );
    console.log(`💾 URLs: ${outTxt}`);

    // Display
    console.log('\n📌 Results:');
    allPins.slice(0, 15).forEach((pin, i) => {
        console.log(`  [${i + 1}] ${pin.title || '(no title)'}`);
        if (pin.pinner) console.log(`       Pinner: ${pin.pinner}`);
        if (pin.hq) console.log(`       HQ: ${pin.hq.slice(0, 85)}...`);
        if (pin.link) console.log(`       Link: ${pin.link}`);
    });

    return allPins;
}

main()
    .then((pins) => {
        console.log(`\n✅ Done! ${pins.length} pins`);
        process.exit(0);
    })
    .catch((err) => {
        console.error('Fatal:', err.message);
        process.exit(1);
    });
