/**
 * Pinterest Network Sniffer - intercept API calls
 * Usage: node unused/sniff_pinterest.js "mirai kuriyama"
 *
 * Uses Puppeteer to intercept all XHR/fetch requests Pinterest makes,
 * so we can find the actual API endpoint that returns pin data.
 */

import puppeteer from 'puppeteer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Netscape cookies
const NETSCAPE_COOKIE_DATA = `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
id.pinterest.com	FALSE	/	FALSE	1799809421	g_state	{"i_l":0,"i_ll":1784257421644,"i_b":"0lxJPEI0owKHR6ml7468ycofO5JxnjASOBrM4y/pF3s","i_e":{"enable_itp_optimization":24},"i_et":1784257421644}
id.pinterest.com	FALSE	/	TRUE	1787025223	csrftoken	cb2840e30da20bf4c1b3130211884101
#HttpOnly_id.pinterest.com	FALSE	/	FALSE	1784343229	_routing_id	"a2f49ad0-6fc1-4439-9f44-5d369c2e99c2"
.pinterest.com	TRUE	/	FALSE	1810784665	_b	"AZNDwjyOHs5CabXN1yP/y5MyvNkxKwyXEGW0lLZuCS+Q3XdJkIvP5s3inPAK53dXSZ4="
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_pinterest_sess	TWc9PSZJTUc4d2NQVmt4cmFWN3pQaXNJOURvaVZvczI2bVZKSmhKK0xFQXVlLzJWQkdubWRiWWZKMjdLN0pUOGZQL3B2TW52OWVsM1hDZ0NTaS9laEhLMDFZUVpMemlLUWFUelJoZDM3N1VEZVFwTjM5Z21ad2txdGIzYjZybzdueEpUME1qU2o2Smc0QXpMNjlCMXZBSlM4QVBNQVo3cTVxSFRnZmJBbHRCaU9Sb0xiQ1h4QkFzcE5xRFFzbVd2UkR6OVk0MEJMdjMzVlZnZjMzUU9Zc0NZaTZXZGx6cW5FdjhWS0dYS2xCSGxlRC9RYWlzUy9uOG5YSmdBTkNXaUdJaTRlU00xYVZ1ck9UWTdvNWpXcU42U2d3b1RNeUhNSG9CSUNvdWVoVkV6Z2VleXFGVmc1b1FSQTIwaGZ6RGJaYjJwNEJFSWRBMXlhaytCQnRjeVcwSENmR3RnSFh3STJ3TE5zbmkzdEhBYXp5NXhaOUNYS0hlY21VR2NqWjgzRnpGbGtqeXRUZHBEMERNVk1RZmYwNlVreUdnPT0mRVNENWhMVExTNEFqRUtJUCt4Smxsdllsbmc0PQ==
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1815634075	usersync	%7B%22magnite%22%3A%7B%22id%22%3A%22MC3IL7OY-1M-30XT%22%2C%22ts%22%3A1784098076459%7D%7D
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	__Secure-s_a	djhOckxoeUNYQW1DT3owWXBNY3lmUHZ6SCtFQjBmKzZUUzRJcUsxeW5PN2xiS1FucVF3dDFPY1llczFrRHV1cmxyTmMwRGVPKytLLzRyeGpBaWpYTE00a3dLZlpYT1NXZUFWLzBaMGpkQ0w1ditwUWt3M3VGQy9iSzhseEJJRlF2RDRuL3E1NHhYVmpqcHk3WXBLb0NvZ1lVSHdWcCtCcThFUEhUMUhVRGJrNDRXT3pVN1V6VXJIdG1Tdm9pWVc0NkhZVnM1RU8vUTZDOU9hYmYvRzVWRUl4NmJhVC9vV0M1WmVzdExXUDFucmJ1VHR0ZmUyN2tQWEd6TGRIVXczTytzdkY3dUVBK3VSeEhiZW5rUjIvNmprVE96dkQrNFJMMGVaOWFGRjN4b289JlFhMytqeGFtL1RuN3pSd0pocThjaG5WNGV4az0=
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1787450543	_auth	1
#HttpOnly_.pinterest.com	TRUE	/	TRUE	1808974505	ar_debug	1
#HttpOnly_id.pinterest.com	FALSE	/	TRUE	1791265976	ar_debug	1
id.pinterest.com	FALSE	/	TRUE	1784300033	sessionFunnelEventLogged	1`;

function parseNetscape(cookieData) {
    const cookies = [];
    const lines = cookieData.split('\n');
    for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed.startsWith('#') || trimmed === '') continue;
        const cleanLine = trimmed.replace(/^#HttpOnly_/, '');
        const parts = cleanLine.split('\t');
        if (parts.length >= 7) {
            const [domain, flag, cookiePath, secure, expiry, name, ...valueParts] = parts;
            let value = valueParts.join('\t');
            if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
            cookies.push({
                name,
                value,
                domain: domain.startsWith('.') ? domain : domain,
                path: cookiePath || '/',
                secure: secure === 'TRUE',
                httpOnly: trimmed.startsWith('#HttpOnly_'),
                expires: parseInt(expiry) || -1,
            });
        }
    }
    return cookies;
}

async function sniffPinterest(query) {
    const searchUrl = `https://id.pinterest.com/search/pins/?q=${encodeURIComponent(query)}&rs=typed`;
    const outputDir = path.join(__dirname, '..', 'results');
    await fs.ensureDir(outputDir);

    console.log('='.repeat(70));
    console.log('  Pinterest Network Sniffer');
    console.log(`  Query: "${query}"`);
    console.log('='.repeat(70));

    const browser = await puppeteer.launch({
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-zygote',
            '--disable-gpu',
            '--hide-scrollbars',
            '--disable-blink-features=AutomationControlled',
            '--window-size=1920,1080',
        ],
    });

    try {
        const page = await browser.newPage();
        await page.setUserAgent(
            'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
        );
        await page.setViewport({ width: 1920, height: 1080 });

        // Anti-detection
        await page.evaluateOnNewDocument(() => {
            Object.defineProperty(navigator, 'webdriver', { get: () => false });
            Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
            Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en', 'id'] });
            window.chrome = { runtime: {}, loadTimes: () => {}, csi: () => {}, app: {} };
        });

        // === NETWORK INTERCEPTION ===
        const apiCalls = [];
        const seenUrls = new Set();

        await page.setRequestInterception(true);

        page.on('request', (request) => {
            const url = request.url();
            const type = request.resourceType();
            const method = request.method();

            // Log interesting requests
            if (
                (type === 'xhr' || type === 'fetch' || type === 'script') &&
                (url.includes('/resource/') ||
                    url.includes('api.pinterest') ||
                    url.includes('/v3/') ||
                    url.includes('/search/') ||
                    (url.includes('pinterest.com') && (url.includes('?') || url.includes('data='))))
            ) {
                const key = url.split('?')[0];
                if (!seenUrls.has(key)) {
                    seenUrls.add(key);
                    try {
                        const postData = request.postData();
                        apiCalls.push({
                            url: url,
                            method: method,
                            type: type,
                            headers: request.headers(),
                            postData: postData || null,
                            timestamp: Date.now(),
                        });
                    } catch (e) {}
                }
            }
            request.continue();
        });

        // Capture response bodies
        const responseBodies = [];

        page.on('response', async (response) => {
            const url = response.url();
            if (
                (url.includes('/resource/') ||
                    url.includes('api.pinterest') ||
                    url.includes('/v3/') ||
                    url.includes('/search/')) &&
                response.status() === 200
            ) {
                const contentType = response.headers()['content-type'] || '';
                if (contentType.includes('json') || contentType.includes('javascript')) {
                    try {
                        const body = await response.text();
                        if (body.length > 100 && body.length < 5000000) {
                            // 5MB limit
                            responseBodies.push({
                                url: url,
                                status: response.status(),
                                contentType: contentType,
                                bodyLength: body.length,
                                body: body.slice(0, 50000), // Truncate for safety
                                timestamp: Date.now(),
                            });
                        }
                    } catch (e) {
                        // Can't read body (stream already consumed, etc)
                    }
                }
            }
        });

        // === NAVIGATE ===
        // 1. Go to home
        console.log('\n🌐 Opening Pinterest home...');
        await page.goto('https://id.pinterest.com/', { waitUntil: 'networkidle2', timeout: 30000 });

        // 2. Set cookies
        const cookies = parseNetscape(NETSCAPE_COOKIE_DATA);
        console.log(`🍪 Setting ${cookies.length} cookies...`);
        await page.setCookie(...cookies);

        // 3. Reload to apply cookies
        await page.goto('https://id.pinterest.com/', { waitUntil: 'networkidle2', timeout: 30000 });

        const loginUrl = page.url();
        const isLoggedIn = !loginUrl.includes('/login/');
        console.log(`🔐 Login: ${isLoggedIn ? '✅ YES' : '❌ NO (redirected to login)'}`);

        // 4. Navigate to search
        console.log(`\n🔍 Searching "${query}"...`);
        await page.goto(searchUrl, { waitUntil: 'networkidle2', timeout: 60000 });
        console.log(`📍 URL: ${page.url()}`);
        console.log(`📄 Title: ${await page.title()}`);

        // 5. Scroll and wait for API calls
        console.log('\n🖱️ Scrolling to trigger API calls...');
        for (let i = 0; i < 6; i++) {
            await page.evaluate(() => {
                window.scrollBy(0, window.innerHeight * 1.5);
            });
            await new Promise((r) => setTimeout(r, 2000));
        }

        // Wait a bit more for any remaining requests
        await new Promise((r) => setTimeout(r, 3000));

        // === SAVE RESULTS ===
        const timestamp = Date.now();

        // Save API calls log
        const apiPath = path.join(outputDir, `pinterest_api_calls_${timestamp}.json`);
        await fs.writeJson(apiPath, apiCalls, { spaces: 2 });
        console.log(`\n📡 API calls logged: ${apiCalls.length}`);
        console.log(`💾 Saved to: ${apiPath}`);

        // Save response bodies that might contain pin data
        const respPath = path.join(outputDir, `pinterest_responses_${timestamp}.json`);
        // Only keep responses that look like they contain data (not just error/empty)
        const usefulResponses = responseBodies.filter((r) => {
            return (
                r.body.includes('pin') ||
                r.body.includes('resource') ||
                r.body.includes('images') ||
                r.body.includes('items') ||
                r.body.includes('results') ||
                r.body.includes('data')
            );
        });
        await fs.writeJson(respPath, usefulResponses.slice(0, 50), { spaces: 2 });
        console.log(
            `📦 Response bodies saved: ${usefulResponses.length} useful out of ${responseBodies.length} total`
        );
        console.log(`💾 Saved to: ${respPath}`);

        // ===== DISPLAY SUMMARY =====
        console.log('\n' + '='.repeat(70));
        console.log('📋 API CALLS SUMMARY');
        console.log('='.repeat(70));

        // Group by endpoint pattern
        const patterns = {};
        for (const call of apiCalls) {
            const key =
                call.url.split('?')[0].split('/').slice(-3).join('/') || call.url.split('?')[0];
            if (!patterns[key]) patterns[key] = [];
            patterns[key].push(call);
        }

        console.log('\n🔗 Unique API Endpoints:');
        for (const [pattern, calls] of Object.entries(patterns)) {
            const sampleUrl = calls[0].url.slice(0, 150);
            console.log(`\n  ${calls.length}x ${pattern}`);
            console.log(`     ${sampleUrl}...`);
        }

        // Highlight the most promising endpoints
        console.log('\n⭐ Most promising endpoints (likely contain pin data):');
        const promising = apiCalls.filter(
            (c) =>
                c.url.toLowerCase().includes('search') ||
                c.url.toLowerCase().includes('pin') ||
                c.url.toLowerCase().includes('resource')
        );
        for (const call of promising.slice(0, 10)) {
            console.log(`  • ${call.method} ${call.url.slice(0, 180)}`);
        }

        // Also save raw HTML for DOM analysis
        const html = await page.content();
        const htmlPath = path.join(outputDir, 'pinterest_sniff.html');
        await fs.writeFile(htmlPath, html.slice(0, 300000));
        console.log(`\n💾 HTML snapshot saved`);

        // Screenshot
        await page.screenshot({
            path: path.join(outputDir, 'pinterest_sniff.png'),
            fullPage: true,
        });
        console.log('📸 Screenshot saved');

        // Try extracting pinimg images from the DOM as well
        const pinImages = await page.evaluate(() => {
            const results = [];
            const seen = new Set();
            document.querySelectorAll('img[src*="pinimg"]').forEach((img) => {
                const src = img.src || '';
                if (src.includes('/avatars/') || src.includes('/favicon')) return;
                if (seen.has(src)) return;
                seen.add(src);
                const parent = img.closest('a');
                results.push({
                    src: src,
                    alt: img.alt || '',
                    link: parent ? parent.href || '' : '',
                    width: img.naturalWidth || img.width,
                    height: img.naturalHeight || img.height,
                });
            });
            return results;
        });

        if (pinImages.length > 0) {
            const imgPath = path.join(outputDir, `pinterest_images_${timestamp}.json`);
            await fs.writeJson(imgPath, pinImages, { spaces: 2 });
            console.log(`\n🖼️ ${pinImages.length} pin images extracted from DOM`);
            console.log('💾 Preview:');
            pinImages.slice(0, 5).forEach((img, i) => {
                console.log(`  [${i + 1}] ${img.alt || '(no alt)'} - ${img.src.slice(0, 80)}...`);
            });
        }

        return { apiCalls, responseBodies, pinImages };
    } catch (err) {
        console.error('❌ Error:', err.message);
        return { apiCalls: [], responseBodies: [], pinImages: [] };
    } finally {
        await browser.close();
        console.log('\n🛑 Browser closed.');
    }
}

// === MAIN ===
const query = process.argv[2] || 'mirai kuriyama';
sniffPinterest(query)
    .then((result) => {
        const total =
            result.apiCalls.length + result.responseBodies.length + result.pinImages.length;
        console.log(`\n✅ Sniffing complete! Total items captured: ${total}`);
        process.exit(0);
    })
    .catch((err) => {
        console.error('Fatal:', err.message);
        process.exit(1);
    });
